export const IMG_ESTRADE = [
  {
    src: "/images/charpentes/estrade/1es.jpg",
    alt: "1",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/estrade/2es.jpg",
    alt: "2",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/estrade/3es.jpg",
    alt: "3",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/estrade/4es.jpg",
    alt: "4",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/estrade/5es.jpg",
    alt: "5",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/estrade/6es.jpg",
    alt: "6",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/estrade/7es.jpg",
    alt: "7",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/estrade/8es.jpg",
    alt: "8",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/estrade/9es.jpg",
    alt: "9",
    width: 1000,
    height: 800,
  },
];

export const IMG_EXTENSION = [
  {
    src: "/images/charpentes/extension/1ext.jpg",
    alt: "1",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/2ext.jpg",
    alt: "2",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/3ext.jpg",
    alt: "3",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/4ext.jpg",
    alt: "4",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/5ext.jpg",
    alt: "5",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/6ext.jpg",
    alt: "6",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/7ext.jpg",
    alt: "7",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/8ext.jpg",
    alt: "8",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/9ext.jpg",
    alt: "9",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/10ext.jpg",
    alt: "10",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/extension/11ext.jpg",
    alt: "11",
    width: 1000,
    height: 800,
  },
];

export const IMG_STAND = [
  {
    src: "/images/charpentes/stand/stand/1st.jpg",
    alt: "1",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/2st.jpg",
    alt: "2",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/3st.jpg",
    alt: "3",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/4st.jpg",
    alt: "4",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/5st.jpg",
    alt: "5",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/6st.jpg",
    alt: "6",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/7st.jpg",
    alt: "7",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/8st.jpg",
    alt: "8",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/9st.jpg",
    alt: "9",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/10st.jpg",
    alt: "10",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/charpentes/stand/stand/11st.jpg",
    alt: "11",
    width: 1000,
    height: 800,
  },
];

export const IMG_CUISINE = [
  {
    src: "/images/cuisine/1cuis.jpg",
    alt: "1",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/cuisine/2cuis.jpg",
    alt: "2",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/cuisine/3cuis.jpg",
    alt: "3",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/cuisine/4cuis.jpg",
    alt: "4",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/cuisine/5cuis.jpg",
    alt: "5",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/cuisine/6cuis.jpg",
    alt: "6",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/cuisine/7cuis.jpg",
    alt: "7",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/cuisine/8cuis.jpg",
    alt: "8",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/cuisine/9cuis.jpg",
    alt: "9",
    width: 1000,
    height: 800,
  },
];

export const IMG_ENSEIGNES = [
  {
    src: "/images/enseignes/1ens.jpg",
    alt: "1",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/2ens.jpg",
    alt: "2",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/3ens.jpg",
    alt: "3",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/4ens.jpg",
    alt: "4",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/5ens.jpg",
    alt: "5",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/6ens.jpg",
    alt: "6",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/7ens.jpg",
    alt: "7",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/8ens.jpg",
    alt: "8",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/9ens.jpg",
    alt: "9",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/10ens.jpg",
    alt: "10",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/11ens.jpg",
    alt: "11",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/12ens.jpg",
    alt: "12",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/13ens.jpg",
    alt: "13",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/14ens.jpg",
    alt: "14",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/15ens.jpg",
    alt: "15",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/16ens.jpg",
    alt: "16",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/17ens.jpg",
    alt: "17",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/18ens.jpg",
    alt: "18",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/19ens.jpg",
    alt: "19",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/20ens.jpg",
    alt: "20",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/21ens.jpg",
    alt: "21",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/22ens.jpg",
    alt: "22",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/23ens.jpg",
    alt: "23",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/24ens.jpg",
    alt: "24",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/25ens.jpg",
    alt: "25",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/26ens.jpg",
    alt: "26",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/27ens.jpg",
    alt: "27",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/28ens.jpg",
    alt: "28",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/29ens.JPEG",
    alt: "29",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/30ens.JPEG",
    alt: "30",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/31ens.JPEG",
    alt: "31",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/32ens.JPEG",
    alt: "32",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/33ens.jpg",
    alt: "33",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/34ens.jpg",
    alt: "34",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/35ens.jpg",
    alt: "35",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/36ens.jpg",
    alt: "36",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/37ens.jpg",
    alt: "37",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/38ens.jpg",
    alt: "38",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/39ens.jpg",
    alt: "39",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/40ens.jpg",
    alt: "40",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/41ens.jpg",
    alt: "41",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/42ens.jpg",
    alt: "42",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/43ens.jpg",
    alt: "43",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/44ens.jpg",
    alt: "44",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/45ens.jpg",
    alt: "45",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/46ens.jpg",
    alt: "46",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/47ens.jpg",
    alt: "47",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/48ens.JPEG",
    alt: "48",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/49ens.JPEG",
    alt: "49",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/50ens.JPEG",
    alt: "50",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/51ens.JPEG",
    alt: "51",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/52ens.JPEG",
    alt: "52",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/53ens.JPEG",
    alt: "53",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/54ens.JPEG",
    alt: "54",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/55ens.JPEG",
    alt: "55",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/56ens.JPEG",
    alt: "56",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/57ens.jpg",
    alt: "57",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/58ens.jpg",
    alt: "58",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/59ens.jpg",
    alt: "59",
    width: 1000,
    height: 800,
  },
];

export const IMG_ENS_BOUCHERIE = [
  {
    src: "/images/enseignes/boucherie/1bouch.JPEG",
    alt: "1",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/boucherie/2bouch.jpeg",
    alt: "2",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/boucherie/3bouch.JPEG",
    alt: "3",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/boucherie/4bouch.JPEG",
    alt: "4",
    width: 1000,
    height: 800,
  },
];
export const IMG_ENS_SIGNATURE = [
  {
    src: "/images/enseignes/signature/1sign.JPEG",
    alt: "1",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/signature/2sign.JPEG",
    alt: "2",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/enseignes/signature/3sign.JPEG",
    alt: "3",
    width: 1000,
    height: 800,
  },
];
export const IMG_MOBILIER = [
  {
    src: "/images/mobilier/1mob.jpg",
    alt: "1",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/2mob.jpg",
    alt: "2",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/3mob.jpg",
    alt: "3",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/4mob.jpg",
    alt: "4",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/5mob.jpg",
    alt: "5",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/6mob.JPEG",
    alt: "6",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/7mob.jpg",
    alt: "7",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/8mob.jpg",
    alt: "8",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/9mob.jpg",
    alt: "9",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/10mob.jpg",
    alt: "10",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/11mob.jpg",
    alt: "11",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/12mob.jpg",
    alt: "12",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/13mob.jpg",
    alt: "13",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/14mob.jpg",
    alt: "14",
    width: 1000,
    height: 800,
  },
  {
    src: "/images/mobilier/15mob.jpg",
    alt: "15",
    width: 1000,
    height: 800,
  },
];
